authapp/urls.py
from django.urls import path

from authapp import views
from authapp.apps import AuthappConfig

app_name = AuthappConfig.name

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("profile_edit/<int:pk>", views.ProfileEditView.as_view(), name="profile_edit"),
    path("password/", views.PasswordsChangeView.as_view(), name="change_password"),
]

config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", RedirectView.as_view(url="mainapp/")),
    path("social_auth/", include("social_django.urls", namespace="social")),
    path("mainapp/", include("mainapp.urls", namespace="mainapp")),
    path("authapp/", include("authapp.urls", namespace="authapp")),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mainapp import views
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path("", views.MainPageView.as_view(), name="main_page"),
    path("news/", views.NewsListView.as_view(), name="news"),
    path("news/create/", views.NewsCreateView.as_view(), name="news_create"),
    path(
        "news/<int:pk>/detail",
        views.NewsDetailView.as_view(),
        name="news_detail",
    ),
    path(
        "news/<int:pk>/update",
        views.NewsUpdateView.as_view(),
        name="news_update",
    ),
    path(
        "news/<int:pk>/delete",
        views.NewsDeleteView.as_view(),
        name="news_delete",
    ),
    path(
        "courses/",
        cache_page(60 * 5)(views.CoursesListView.as_view()),  # 5 minutes
        name="courses",
    ),
    path(
        "courses/<int:pk>/",
        views.CoursesDetailView.as_view(),
        name="courses_detail",
    ),
    path(
        "course_feedback/",
        views.CourseFeedbackFormProcessView.as_view(),
        name="course_feedback",
    ),
    path("contacts/", views.ContactsPageView.as_view(), name="contacts"),
    path("doc_site/", views.DocSitePageView.as_view(), name="doc_site"),
    path("log_view/", views.LogView.as_view(), name="log_view"),
    path("log_download/", views.LogDownloadView.as_view(), name="log_download"),
]

templates/includes/main_menu.html
{% load static i18n %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'mainapp:main_page' %}">
      <img src="{% static 'img/logo.png' %}" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li
          class="nav-item {% if request.resolver_match.view_name == 'mainapp:news' %}active{% endif %}">
          <a class="nav-link" href="{% url 'mainapp:news' %}">
            {% translate "News" %}
          </a>
        </li>
        <li
          class="nav-item {% if request.resolver_match.view_name == 'mainapp:courses' %}active{% endif %}">
          <a class="nav-link" href="{% url 'mainapp:courses' %}">
            {% translate "Courses" %}
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="ddProfile"
            role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            {% translate "Profile" %}
          </a>
          <div class="dropdown-menu" aria-labelledby="ddProfile">
            <a class="dropdown-item"
              href="{% url 'authapp:profile_edit' pk=request.user.pk %}">Редактировать
              профиль</a>
            <a class="dropdown-item" href="#">Мои курсы</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Модерация</a>
            {% if user.is_superuser %}
            <a class="dropdown-item" href="{% url 'admin:index' %}"
              target="_blank">Административный
              раздел</a>
            <a class="dropdown-item" href="{% url 'mainapp:log_view' %}"
              target="_blank">Лог</a>
            {% endif %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'authapp:logout' %}">Выход</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authapp:login' %}">
            {% translate "Enter" %}
          </a>
        </li>
        {% endif %}
        <li
          class="nav-item {% if request.resolver_match.view_name == 'mainapp:contacts' %}active{% endif %}">
          <a class="nav-link" href="{% url 'mainapp:contacts' %}">
            {% translate "Contacts" %}
          </a>
        </li>
      </ul>
      <div class="row justify-content-end m-0">
        <div class="col p-0 border-right">
          <form action="{% url 'set_language' %}" method="post">
            {% csrf_token %}
            <input name="language" type="hidden" value="ru">
            <button type="submit" class="btn btn-link">🇷🇺</button>
          </form>
        </div>
        <div class="col p-0 border-left">
          <form action="{% url 'set_language' %}" method="post">
            {% csrf_token %}
            <input name="language" type="hidden" value="en">
            <button type="submit" class="btn btn-link">🇬🇧</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</nav>

templates/includes/messages.html
<div class="position-absolute w-100" style="z-index: 1;">
  <div aria-live="polite" aria-atomic="true" class="m-2">
    <!-- Position it -->
    <div class="d-flex align-items-end flex-column">

      {% for message in messages %}
      <!-- Then put toasts within -->
      <div class="toast flex-fill w-100
    {% if message.level == 30 %}
    border-warning
    {% endif %}
      " role="alert" aria-live="assertive" aria-atomic="true"
        style="right: 0;">
        <div class="toast-header">
          <span class="mr-2"><i class="far fa-envelope"></i></span>
          <strong
            class="mr-auto {% if message.level == 30 %}text-warning{% endif %}">
            {{ message.tags|capfirst }} message</strong>
          <small class="text-muted">just now</small>
          <button type="button" class="ml-2 mb-1 close" data-dismiss="toast"
            aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="toast-body">
          {{ message }}
        </div>
      </div>
      {% if message.level > 20 %}
      <!-- If message will dissapere you will find message in console -->
      <script>
        console.log("{{ message }}");
      </script>
      {% endif %}

      {% endfor %}

    </div>

  </div>
</div>