config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", RedirectView.as_view(url="mainapp/")),
    path("social_auth/", include("social_django.urls", namespace="social")),
    path("mainapp/", include("mainapp.urls", namespace="mainapp")),
    path("authapp/", include("authapp.urls", namespace="authapp")),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mainapp import views
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path("", views.MainPageView.as_view(), name="main_page"),
    path("news/", views.NewsListView.as_view(), name="news"),
    path("news/create/", views.NewsCreateView.as_view(), name="news_create"),
    path(
        "news/<int:pk>/detail",
        views.NewsDetailView.as_view(),
        name="news_detail",
    ),
    path(
        "news/<int:pk>/update",
        views.NewsUpdateView.as_view(),
        name="news_update",
    ),
    path(
        "news/<int:pk>/delete",
        views.NewsDeleteView.as_view(),
        name="news_delete",
    ),
    path(
        "courses/",
        cache_page(60 * 5)(views.CoursesListView.as_view()),  # 5 minutes
        name="courses",
    ),
    path(
        "courses/<int:pk>/",
        views.CoursesDetailView.as_view(),
        name="courses_detail",
    ),
    path(
        "course_feedback/",
        views.CourseFeedbackFormProcessView.as_view(),
        name="course_feedback",
    ),
    path("contacts/", views.ContactsPageView.as_view(), name="contacts"),
    path("doc_site/", views.DocSitePageView.as_view(), name="doc_site"),
    path("log_view/", views.LogView.as_view(), name="log_view"),
    path("log_download/", views.LogDownloadView.as_view(), name="log_download"),
]

mainapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

class ObjectManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class News(models.Model):
    objects = ObjectManager()
    title = models.CharField(max_length=256, verbose_name="Title")
    preambule = models.CharField(max_length=1024, verbose_name="Preambule")
    body = models.TextField(blank=True, null=True, verbose_name="Body")
    body_as_markdown = models.BooleanField(
        default=False, verbose_name="As markdown"
    )
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Created", editable=False
    )
    updated = models.DateTimeField(
        auto_now=True, verbose_name="Edited", editable=False
    )
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _("News")
        verbose_name_plural = _("News")
        ordering = ("-created",)

class Courses(models.Model):
    objects = ObjectManager()

    name = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(
        verbose_name="Description", blank=True, null=True
    )
    description_as_markdown = models.BooleanField(
        verbose_name="As markdown", default=False
    )
    cost = models.DecimalField(
        max_digits=8, decimal_places=2, verbose_name="Cost", default=0
    )
    cover = models.CharField(
        max_length=25, default="no_image.svg", verbose_name="Cover"
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.name}"

    def delete(self, *args):
        self.deleted = True
        self.save()


class Lesson(models.Model):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Lesson number")
    title = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(
        verbose_name="Description", blank=True, null=True
    )
    description_as_markdown = models.BooleanField(
        verbose_name="As markdown", default=False
    )
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Created", editable=False
    )
    updated = models.DateTimeField(
        auto_now=True, verbose_name="Edited", editable=False
    )
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.course.name} | {self.num} | {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        ordering = ("course", "num")


class CourseTeachers(models.Model):
    course = models.ManyToManyField(Courses)
    name_first = models.CharField(max_length=128, verbose_name="Name")
    name_second = models.CharField(max_length=128, verbose_name="Surname")
    day_birth = models.DateField(verbose_name="Birth date")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return "{0:0>3} {1} {2}".format(
            self.pk, self.name_second, self.name_first
        )

    def delete(self, *args):
        self.deleted = True
        self.save()


class CourseFeedback(models.Model):
    RATING = ((5, "⭐⭐⭐⭐⭐"), (4, "⭐⭐⭐⭐"), (3, "⭐⭐⭐"), (2, "⭐⭐"), (1, "⭐"))
    course = models.ForeignKey(
        Courses, on_delete=models.CASCADE, verbose_name=_("Course")
    )
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, verbose_name=_("User")
    )
    feedback = models.TextField(
        default=_("No feedback"), verbose_name=_("Feedback")
    )
    rating = models.SmallIntegerField(
        choices=RATING, default=5, verbose_name=_("Rating")
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.course} ({self.user})"

mainapp/views.py
from datetime import datetime
from django.core.cache import cache
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse, JsonResponse, FileResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib import messages
from config import settings
from mainapp import models as mainapp_models, mainapp_forms
import logging
from django.http.response import HttpResponseRedirect
from django.utils.translation import gettext_lazy as _
from mainapp import tasks as mainapp_tasks


logger = logging.getLogger(__name__)


class MainPageView(TemplateView):
    template_name = "mainapp/index.html"


class NewsListView(ListView):
    model = mainapp_models.News
    paginate_by = 5

    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class NewsCreateView(PermissionRequiredMixin, CreateView):
    model = mainapp_models.News
    fields = "__all__"
    success_url = reverse_lazy("mainapp:news")
    permission_required = ("mainapp.add_news",)


class NewsDetailView(DetailView):
    model = mainapp_models.News


class NewsUpdateView(PermissionRequiredMixin, UpdateView):
    model = mainapp_models.News
    fields = "__all__"
    success_url = reverse_lazy("mainapp:news")
    permission_required = ("mainapp.change_news",)


class NewsDeleteView(PermissionRequiredMixin, DeleteView):
    model = mainapp_models.News
    success_url = reverse_lazy("mainapp:news")
    permission_required = ("mainapp.delete_news",)


class CoursesListView(TemplateView):
    template_name = "mainapp/courses.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["objects"] = mainapp_models.Courses.objects.all()[:7]
        return context


class CoursesDetailView(TemplateView):
    template_name = "mainapp/courses_detail.html"

    def get_context_data(self, pk=None, **kwargs):
        logger.debug("Yet another log message")
        context = super(CoursesDetailView, self).get_context_data(**kwargs)
        context["course_object"] = get_object_or_404(
            mainapp_models.Courses, pk=pk
        )
        context["lessons"] = mainapp_models.Lesson.objects.filter(
            course=context["course_object"]
        )
        context["teachers"] = mainapp_models.CourseTeachers.objects.filter(
            course=context["course_object"]
        )
        if not self.request.user.is_anonymous:
            if not mainapp_models.CourseFeedback.objects.filter(
                course=context["course_object"], user=self.request.user
            ).count():
                context["feedback_form"] = mainapp_forms.CourseFeedbackForm(
                    course=context["course_object"], user=self.request.user
                )

        cached_feedback = cache.get(f"feedback_list_{pk}")
        if not cached_feedback:
            context["feedback_list"] = (
                mainapp_models.CourseFeedback.objects.filter(
                    course=context["course_object"]
                )
                .order_by("-created", "-rating")[:5]
                .select_related()
            )
            cache.set(
                f"feedback_list_{pk}", context["feedback_list"], timeout=300
            )  # 5 minutes

            # Archive object for tests --->
            import pickle
            with open(
                f"mainapp/fixtures/006_feedback_list_{pk}.bin", "wb"
            ) as outf:
                pickle.dump(context["feedback_list"], outf)
            # <--- Archive object for tests

        else:
            context["feedback_list"] = cached_feedback

        return context


class CourseFeedbackFormProcessView(LoginRequiredMixin, CreateView):
    model = mainapp_models.CourseFeedback
    form_class = mainapp_forms.CourseFeedbackForm

    def form_valid(self, form):
        self.object = form.save()
        rendered_card = render_to_string(
            "mainapp/includes/feedback_card.html", context={"item": self.object}
        )
        return JsonResponse({"card": rendered_card})



class ContactsPageView(TemplateView):
    template_name = "mainapp/contacts.html"

    def get_context_data(self, **kwargs):
        context = super(ContactsPageView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["form"] = mainapp_forms.MailFeedbackForm(
                user=self.request.user
            )
        return context

    def post(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            cache_lock_flag = cache.get(
                f"mail_feedback_lock_{self.request.user.pk}"
            )
            if not cache_lock_flag:
                cache.set(
                    f"mail_feedback_lock_{self.request.user.pk}",
                    "lock",
                    timeout=300,
                )
                messages.add_message(
                    self.request, messages.INFO, _("Message sended")
                )
                mainapp_tasks.send_feedback_mail.delay(
                    {
                        "user_id": self.request.POST.get("user_id"),
                        "message": self.request.POST.get("message"),
                    }
                )
            else:
                messages.add_message(
                    self.request,
                    messages.WARNING,
                    _("You can send only one message per 5 minutes"),
                )
        return HttpResponseRedirect(reverse_lazy("mainapp:contacts"))



class DocSitePageView(TemplateView):
    template_name = "mainapp/doc_site.html"


class LoginPageView(TemplateView):
    template_name = "mainapp/login.html"


class LogView(TemplateView):
    template_name = "mainapp/log_view.html"

    def get_context_data(self, **kwargs):
        context = super(LogView, self).get_context_data(**kwargs)
        log_slice = []
        with open(settings.LOG_FILE, "r") as log_file:
            for i, line in enumerate(log_file):
                if i == 1000:  # first 1000 lines
                    break
                log_slice.insert(0, line)  # append at start
            context["log"] = "".join(log_slice)
        return context


class LogDownloadView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser

    def get(self, *args, **kwargs):
        return FileResponse(open(settings.LOG_FILE, "rb"))

mainapp/templates/mainapp/courses.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Курсы
{% endblock title %}


{% block content %}


    <div class="row justify-content-center mt-3">

                {% for item in objects %}
                <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="{% url 'mainapp:courses_detail' pk=item.pk %}">
                    <img src="{% static item.cover %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-center">{{ item.name }}</h5>
                    </div>
                </a>
                </div>
                {% endfor %}



    </div>
    <div class="row justify-content-center align-items-center mt-3 mb-n3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
  </nav>
</div>

{% endblock content %}

mainapp/templates/mainapp/courses_detail.html
{% extends 'base.html' %}
{% load static markdownify crispy_forms_tags cache %}

{% block title %}
{{ course_object.name }}
{% endblock title %}

{% block content %}
<h1 class="mt-2">
  {{ course_object.name }}
</h1>
<div class="row justify-content-center">
  <div class="col-sm-12 col-md-6 col-lg-8 order-2 order-md-1">
    <div class="row h-100">
      <div class="col-12">
        {% if course_object.description_as_markdown %}
        {{ course_object.description|markdownify }}
        {% else %}
        {{ course_object.description }}
        {% endif %}
      </div>
      <div class="col-12 align-self-end">
        <p>
          <small>Преподаватели</small><br>
          {% for item in teachers %}
          {{ item.name_second }} {{ item.name_first }}{% if forloop.last %}{% else %},{% endif %}
          {% endfor %}
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-6 col-lg-4 order-1 order-md-2">
    <div class="row h-100">
      <div class="col-12 align-self-start">
        <img class="w-100" src="{% static course_object.cover %}">
      </div>
      <div class="col-12 align-self-end d-none d-md-block">
        <p class="text-center mt-2">
          <small class="text-uppercase">цена</small><br>
          <span style="font-size: 30pt;">
            {{ course_object.cost}}
          </span><br>
          <a href="#" class="btn btn-outline-primary btn-block"
            role="button">Купить</a>
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-12 d-md-none order-3 order-sm-3">
    <p class="text-center">
      <small class="text-uppercase">цена</small><br>
      <span style="font-size: 30pt;">
        {{ course_object.cost}}
      </span><br>
      <a href="#" class="btn btn-outline-primary btn-block"
        role="button">Купить</a>
    </p>
  </div>
</div>
<div class="accordion" id="accordionLessons">

  {% cache 300 lessons %}
  {% for item in lessons %}
  <div class="card">
    <div class="card-header" id="headLessonPk{{ item.pk }}">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left" type="button"
          data-toggle="collapse" data-target="#collapse{{ item.pk }}"
          aria-expanded="true" aria-controls="collapse{{ item.pk }}">
          {{ item.course.name }} - {{ item.title }}
        </button>
      </h2>
    </div>

    <div id="collapse{{ item.pk }}" class="collapse"
      aria-labelledby="headLessonPk{{ item.pk }}"
      data-parent="#accordionLessons">
      <div class="card-body">
        <div class="row justify-content-center">
          <div class="col-12 text-center">
            <img src="{% static 'img/no_image.svg' %}" width="250px">
          </div>
          <div class="col-12">
            {% if item.description_as_markdown %}
            {{ item.description|markdownify }}
            {% else %}
            {{ item.description }}
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  {% endcache %}

</div>
<h3>Отзывы</h3>

<div id="feedback_list">
  {% if feedback_list %}
  {% for item in feedback_list %}
  {% include 'mainapp/includes/feedback_card.html' %}
  {% endfor %}
  {% else %}
  <p>
    No feedback yet. Be first!
  </p>
  {% endif %}
</div>

{% if feedback_form %}
<div class="card" id="cardForm">
  <div class="card-body">
    <h5 class="card-title">Добавить отзыв</h5>
    <h6 class="card-subtitle mb-2 text-muted">Вы ещё не оставляли отзыв к этому
      курсу</h6>
    <p class="card-text">
    <form action="{% url 'mainapp:course_feedback' %}" method="POST"
      id="feedbackForm">
      {% csrf_token %}
      {{ feedback_form|crispy }}
    </form>
    <button id="feedbackSubmit"
      class="btn btn-primary btn-block">Отправить</button>
    </p>
  </div>
</div>
{% endif %}

{% endblock content %}

{% block js %}
<script>
  $(document).ready(function () {

    {% if feedback_form %}
    $("#feedbackSubmit").click(function () {

      $("#cardForm").hide();

      var $form = $("#feedbackForm");
      $.ajax({
        type: "POST",
        url: $form.attr("action"),
        data: $form.serialize(),
        success: function (data) {
          $("#feedback_list").append(data.card);
        }
      });

    });
    {% endif %}

  });
</script>
{% endblock js %}

mainapp/templates/mainapp/doc_site.html
{% extends 'base.html' %}

{% block content %}

        
<div class="row justify-content-center align-items-center mt-3">
  <div class="col-md-9">
    <div class="card">
      <div class="card-header">
        Документация по сайту
      </div>
      <div class="card-body">

        <h5 class="card-title">CSS-стили</h5>
        <p class="card-text">
        <ul>
          <li><a href="https://getbootstrap.com/docs/4.6/getting-started/introduction/" target="_blank">Bootstrap
              v4.6</a></li>
          <li><a href="https://bootswatch.com/lumen/" target="_blank">Bootstrap theme: Lumen</a></li>
        </ul>
        </p>

        <h5 class="card-title">Иконки</h5>
        <p class="card-text">
          <a href="https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use">FontAwesome 5.15.3</a>
        </p>

        <h5 class="card-title">Графики</h5>
        <p class="card-text">
          <a href="https://www.chartjs.org/">ChartJS</a>
        </p>

        <h5 class="card-title">Графика</h5>
        <p class="card-text">
        <ul>
          <li><a href="https://www5.flamingtext.com/" target="_blank" rel="noopener noreferrer">Логотип by
              flamingtext.com</a></li>
          <li><a href="https://www.pexels.com/ru-ru" target="_blank" rel="noopener noreferrer">Фотографии by
              pexels.com</a>. Все изображения распространяются под бесплатной лицензией. Для страницы обзоров фотографии
            должны быть с соотношением сторон кратным 2.912 (например, 1920x659)</li>
          <li><a href="https://getavataaars.com/" target="_blank" rel="noopener noreferrer">Аватарки пользователей by
              getavataaars.com</a></li>
        </ul>
        </p>

      </div>
    </div>
  </div>
</div>

{% endblock content %}

mainapp/templates/mainapp/log_view.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-end my-2">
    <div class="col-sm-4 col-lg-2">
        <a href="{% url 'mainapp:log_download' %}" class="btn btn-primary btn-block"
           role="button">Скачать</a>
    </div>
</div>
<p>
<div class="text-center text-muted"><small>First 1000 lines of log file</small></div>
<pre>{{ log }}</pre>
</p>
{% endblock content %}

mainapp/templates/mainapp/news.html
{% extends 'base.html' %}

{% block content %}

{% with range as double_range %}


<div class="row">

  <div class="col-lg-8">
    {% for item in news_qs %}
    <div class="card my-2">
      <div class="card-body">
        <h5 class="card-title">{{ item.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ item.created|date:"Y-m-d h-i-s" }}</h6>
        <p class="card-text">{{ item.preambule }}</p>
        <a href="{% url 'mainapp:news_detail' pk=item.pk %}" class="card-link">Подробнее</a>
      </div>
    </div>
    {% endfor %}

    
  </div>

  <div class="col-lg-4">
    <div class="card my-2 sticky-top">
      <div class="card-header">
        Фильтры
      </div>
      <div class="card-body">
        <form action="">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата от...</span>
            </div>
            <input type="date" class="form-control" name="dateFrom">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата до...</span>
            </div>
            <input type="date" class="form-control" name="dateTo">
          </div>

          <button type="submit" class="btn btn-primary btn-block">Фильтровать</button>
        </form>
      </div>
    </div>
  </div>

</div>

<div class="row justify-content-center align-items-center mt-3 mb-n3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    <li class="page-item"><a class="page-link" href="">1</a></li>
    <li class="page-item"><a class="page-link" href="">2</a></li>
    {# <li class="page-item"><a class="page-link" href="{% url 'mainapp:news_paginator' three %}">3</a></li> #}
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
  </nav>
</div>

{% endwith %}
{% endblock content %}

mainapp/templates/mainapp/news_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center pt-3">
  <div class="col-md-8 col-lg-6">
    <h2>Пометить новость удалённой?</h2>
    <p>
      Поставить отметку удаления для новости:<br>
      "{{ object.title }}" от {{ object.created }}
    </p>
    <p>
    <div class="row">
      <div class="col-6">
        <form action="{% url 'mainapp:news_delete' pk=object.pk %}"
          method="post">
          {% csrf_token %}
          <button class="btn btn-danger btn-block"
            type="submit">Подтвердить</button>
        </form>
      </div>
      <div class="col-6">
        <a class="btn btn-primary btn-block" href="{% url 'mainapp:news' %}"
          role="button">Отмена</a>
      </div>
    </div>
    </p>
  </div>
</div>
{% endblock content %}

mainapp/templates/mainapp/news_detail.html
{% extends 'base.html' %}

{% block title %}
{{ object.title|default:"Новости" }}
{% endblock title %}

{% block content %}
<div class="row justify-content-center pt-3">
  <div class="col-md-12 col-lg-8">
    <div class="card shadow">
      <div class="card-body">
        <h5 class="card-title">{{ object.title }}</h5>
        <p class="card-text">
          {{ object.body }}
        </p>
        <a href="{% url 'mainapp:news' %}" class="btn btn-primary">Назад</a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

mainapp/templates/mainapp/news_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center pt-3">
  <div class="col-md-12 col-lg-8">
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary btn-block">Опубликовать</button>
    </form>
  </div>
</div>
{% endblock content %}

mainapp/templates/mainapp/news_list.html
{% extends 'base.html' %}

{% block title %}
Новости
{% endblock title %}

{% block content %}

{% if page_num %}
<div class="card my-2">
  <div class="card-body">
    <p class="card-text">Текущая страница: {{ page_num }}</p>
  </div>
</div>
{% endif %}

<div class="row">
  <div class="col-lg-8">

    {% for item in object_list %}
    <div class="card my-2">
      <div class="card-body">
        <h5 class="card-title">{{ item.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          {{ item.created|date:"Y-m-d h-i-s" }}
        </h6>
        <p class="card-text">{{ item.preambule }}</p>
        <div class="row">
          <div class="col">
            <a href="{% url 'mainapp:news_detail' pk=item.pk %}"
              class="card-link">Подробнее</a>
          </div>
          {% if perms.mainapp.change_news %}
          <div class="col-1 text-center">
            <a href="{% url 'mainapp:news_update' pk=item.pk %}">
              <i class="far fa-edit"></i>
            </a>
          </div>
          {% endif %}
          {% if perms.mainapp.delete_news %}
          <div class="col-1 text-center">
            <a href="{% url 'mainapp:news_delete' pk=item.pk %}">
              <i class="far fa-trash-alt"></i>
            </a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}

  </div>

  <div class="col-lg-4">
    <div class="card my-2 sticky-top">
      <div class="card-header">
        Фильтры
      </div>
      <div class="card-body">
        <form action="">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата от...</span>
            </div>
            <input type="date" class="form-control" name="dateFrom">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата до...</span>
            </div>
            <input type="date" class="form-control" name="dateTo">
          </div>

          <button type="submit"
            class="btn btn-primary btn-block">Фильтровать</button>
        </form>
      </div>
    </div>

    {% if perms.mainapp.add_news %}
    <a class="btn btn-primary btn-block" role="button"
      href="{% url 'mainapp:news_create' %}">Добавить новость</a>
    {% endif %}

  </div>

</div>

<div class="row justify-content-center align-items-center mt-3 mb-n3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link"
          href="?page={{ page_obj.previous_page_number }}">Назад</a></li>
      {% endif %}

      {% for item in page_obj.paginator.page_range %}
      <li class="page-item
        {% if item == page_obj.number %}active{% endif %}">
        <a class="page-link" href="?page={{ item }}">{{ item }}</a>
      </li>
      {% endfor %}

      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link"
          href="?page={{ page_obj.next_page_number }}">Следующая</a></li>
      {% endif %}
    </ul>
  </nav>
</div>


{% endblock content %}